### ISSUE TITLE
Flickering of transition Window Animations 

### ISSUE THREAD

**Issue by shaktishekhar** [Grarak/android_device_oneplus_oneplus2#33] opened 2016-06-11 03:55 UTC
Radio/baseband: MPSSS.BO.2.c9-00015-M8994FAAAANAZM-1
Kernel version: 3.10.84
Model: oneplus 2
Component/s: Visual (GUI)
Affects Version/s: 13.0
@Grarak

Flickering of transition Window Animations while opening apps like whatsapp,playstore,Twitter,Bluemail etc..
i can confirm that this issue is only present in cm 13 official nightly .
am on 10th latest official nightly on other phone cm 13 like nexus 6 this issue is not present also not present on official OOS 3.0.2 tested (This issue was also not present in early release of unofficial cm build 13.1 of @Seraph08 (David Vandenburgh)  i have done testing with different Op2 devices they also reported the same hence am reporting here .

Thank You 

Regards' 

Shakti Shekhar

@shaktishekhar "xda" id

Logcat link = [goo.gl/RzYjxp](url)
Sample Video of issue in link = [goo.gl/McN22H](url)
"Copy The Link and paste it in Address bar don't click"

**Comment by Charul1810** [comment] 2016-06-11 04:13
Yes.I can confirm that the flickering happens while opening WhatsApp,playstore, Twitter.The transition lags while opening this apps do lag.

**Comment by DerkSoul** [comment] 2016-06-11 05:08
Yes another the most irritating problem coming up is the tinting of the status bar it flickers alot while the transition of closing or opening of playstore, whatsapp , facebook etc. Please solver this issue because its not present in any other cm13 roms on other phones but is present in the op2 cm13 nightly rom and that to official. Please solve it as fast as possible. 
Thank you

**Comment by MorgulBlade** [comment] 2016-06-11 05:12
Yes, confirmed glitch. Definitely occurs with WhatsApp, playstore and google chrome.

**Comment by mukeshp7867** [comment] 2016-06-11 05:26
Yes. Confirmed this issue. I have seen it happening with WhatsApp all the time. Request developers to solve the same. Thanks in anticipation.

**Comment by friendyy** [comment] 2016-06-11 06:40
Yes i m not facing this is in telegram but in whatsapp and playstore and some apps this problem is present

**Comment by sahilr05** [comment] 2016-06-11 15:05
I'm also facing the same issue in WhatsApp , blue mail , play store , tweeter and few more...
please fix this ....

**Comment by neerajms** [comment] 2016-06-12 04:51
Yes there is a flickering when I open apps like WhatsApp, Play store etc.

**Comment by JoonatanH-Products** [comment] 2016-06-12 08:52
Yes there is a flickering when I open apps like WhatsApp, Play store etc. And it's kind of problematic.

**Comment by shaktishekhar** [comment] 2016-06-13 16:43
@Grarak  One Last Question Can This issue be resolve or not if not just reply no i will close the issue 
am talking about animation issue while opening apps like whatsapp

**Comment by JustArchi** [comment] 2016-06-13 16:59
How about showing some respect for @Grarak and not asking for immediate fix? He's not paid to maintain our device, and it's barely 3 days since you posted your issue. I'd really appreciate if users didn't repeat the same bug over and over again, and instead wait patiently or fix it themselves.

**Closed** 2016-06-13 17:02 UTC
